// Ported from the Next.js source's ServicePartnerInvoiceModal.tsx +
// BaExpressHeader.tsx + ServicePartnerDetailsBlock.tsx (folded into this one
// file — presentation only, no separate header sub-component needed here).
import { createPortal } from 'react-dom';
import { useModalBehavior } from '../../../hooks/useModalBehavior';
import type { Invoice } from '../../../data/servicePartnerInvoicesData';
import { BA_COMPANY } from '../constants/baCompany';
import { formatGbp, formatInvoiceNumber, parsePeriodLabel } from '../utils/format';
import { DeductionsBlock, GrandTotalBar, InvoiceSummaryStats, PartnerInvoiceBlock, VatBlock } from './InvoiceBlocks';

interface Props {
  invoice: Invoice;
  onClose: () => void;
}

export function ServicePartnerInvoiceModal({ invoice, onClose }: Props) {
  useModalBehavior(onClose, true);

  const periodLabel = parsePeriodLabel(invoice.date);
  const totalStops = invoice.itens.reduce((sum, item) => sum + item.totalStops, 0);
  const itemLabel = `${invoice.itens.length} ${invoice.itens.length === 1 ? 'item' : 'items'}`;
  const formattedInvoiceNumber = formatInvoiceNumber(invoice.invoiceNumber);
  const partnerName = invoice.servicePartnerName || `#${invoice.servicePartnerId}`;

  const cards = [
    { label: 'Period', value: periodLabel },
    { label: 'Total Stops', value: String(totalStops) },
    { label: 'Net Total', value: formatGbp(invoice.netTotal), positive: true },
  ];

  return createPortal(
    <div className="spi-modal-overlay" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}>
      <div className="spi-modal spi-modal--xl" role="dialog" aria-modal="true">
        <button type="button" className="spi-modal-close" onClick={onClose} aria-label="Close">
          <i className="bi bi-x-lg" />
        </button>
        <div className="spi-modal-body spi-doc">
          <div className="spi-doc-header">
            <div className="spi-doc-party">
              <p className="spi-doc-party-tag">TO</p>
              <p className="spi-doc-party-name">{BA_COMPANY.name}</p>
              <p className="spi-doc-party-line">{BA_COMPANY.address}</p>
              <p className="spi-doc-party-line">{BA_COMPANY.email}</p>
              <p className="spi-doc-party-line">{BA_COMPANY.vat}</p>
            </div>

            <div className="spi-doc-party">
              <p className="spi-doc-party-tag">FROM</p>
              <p className="spi-doc-party-name">{partnerName}</p>
              {invoice.servicePartnerAddress && <p className="spi-doc-party-line">{invoice.servicePartnerAddress}</p>}
              {invoice.servicePartnerPhone && <p className="spi-doc-party-line">{invoice.servicePartnerPhone}</p>}
              {invoice.servicePartnerVatNumber && <p className="spi-doc-party-line">VAT: {invoice.servicePartnerVatNumber}</p>}
              {!invoice.servicePartnerAddress && !invoice.servicePartnerPhone && !invoice.servicePartnerVatNumber && (
                <p className="spi-doc-party-line spi-doc-party-line--muted">No additional details available</p>
              )}
            </div>

            <div className="spi-doc-box">
              {formattedInvoiceNumber && (
                <div>
                  <p className="spi-doc-box-label">Invoice Number:</p>
                  <p className="spi-doc-box-value">{formattedInvoiceNumber}</p>
                </div>
              )}
              <div>
                <p className="spi-doc-box-label">Date:</p>
                <p className="spi-doc-box-value">{periodLabel}</p>
              </div>
            </div>
          </div>

          <InvoiceSummaryStats cards={cards} />

          <PartnerInvoiceBlock
            partnerName={partnerName}
            issuerLabel={`${BA_COMPANY.name} - ${periodLabel}`}
            items={invoice.itens}
            subtotal={invoice.amountTotal}
          />

          <DeductionsBlock
            deductions={invoice.deductions}
            totalDeductions={invoice.totalDeductions}
            totalReimbursements={invoice.totalReimbursements}
          />

          <VatBlock amount={invoice.totalVat} />

          <GrandTotalBar total={invoice.netTotal} caption={`1 invoice, ${itemLabel}`} />

          <div className="spi-doc-footer">
            <span>Generated by {BA_COMPANY.name}</span>
            <span className="spi-doc-footer-accent">Service Partner Invoices</span>
          </div>
        </div>
      </div>
    </div>,
    document.body,
  );
}
